<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
        <TargetFramework>net8.0-windows</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Model\Character\" />
      <Folder Include="ViewModels\" />
      <Folder Include="View\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Autofac" Version="8.4.0" />
      <PackageReference Include="Autofac.Extras.Moq" Version="7.0.0" />
    </ItemGroup>

</Project>
